/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import com.itextpdf.text.DocumentException;
import control.Control;
import java.awt.Color;
import java.awt.Component;
import java.io.FileNotFoundException;
import java.time.LocalDate;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modelo.Falta;
import modelo.Horario;

/**
 *
 * @author Charly Cimino
 */
public class Informe extends VistaBase {

    /**
     * Creates new form Informe
     */
    public Informe() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CUI = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Apellido = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaFaltas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        Apellido1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Apellido2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Apellido3 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        colores = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        CUI.setEditable(true);
        CUI.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CUIItemStateChanged(evt);
            }
        });

        jLabel1.setText("Codigo");

        jLabel2.setText("Nombre");

        Nombre.setEditable(false);

        jLabel3.setText("Hora Entrada");

        Apellido.setEditable(false);

        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tablaFaltas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Dia", "Entrada", "Alm. Salida", "Alm. Entrada", "Salida"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaFaltas);
        if (tablaFaltas.getColumnModel().getColumnCount() > 0) {
            tablaFaltas.getColumnModel().getColumn(1).setResizable(false);
            tablaFaltas.getColumnModel().getColumn(1).setHeaderValue("Color");
            tablaFaltas.getColumnModel().getColumn(2).setHeaderValue("Alm. Salida");
            tablaFaltas.getColumnModel().getColumn(3).setHeaderValue("Alm. Entrada");
            tablaFaltas.getColumnModel().getColumn(4).setHeaderValue("Salida");
        }

        jLabel5.setText("Hora Salida");

        Apellido1.setEditable(false);

        jLabel6.setText("Hora Salida Almuerzo");

        Apellido2.setEditable(false);

        jLabel7.setText("Hora Entrada del Almuerzo");

        Apellido3.setEditable(false);

        colores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Razón"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(colores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Nombre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 268, Short.MAX_VALUE)
                                    .addComponent(CUI, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Apellido3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(Apellido, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Apellido1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Apellido2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Apellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Apellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Apellido3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(CUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controlador.mostrarVentana(TipoVentana.Ventana.INICIO);
        this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        controlador.llenarLista(CUI);
        DefaultTableModel modeloTabla = (DefaultTableModel) colores.getModel();

        // Limpiar cualquier fila existente
        modeloTabla.setRowCount(0);

        // Lista de motivos que quieres mostrar
        String[] motivos = {
            "Llegada tarde",
            "No marcó",
            "Faltó",
            "Sin falta"
        };

        // Agregar cada motivo como una fila nueva
        for (String m : motivos) {
            modeloTabla.addRow(new Object[]{ m });
        }

        // Asignar el renderer para colorear según el motivo
        colores.setDefaultRenderer(Object.class, new javax.swing.table.DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                                                           boolean isSelected, boolean hasFocus,
                                                           int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                String motivo = value != null ? value.toString() : "";

                // Elegir color según el motivo
                switch (motivo) {
                    case "Llegada tarde":
                        c.setBackground(Color.YELLOW);
                        break;
                    case "No marcó":
                        c.setBackground(Color.ORANGE);
                        break;
                    case "Faltó":
                        c.setBackground(Color.RED);
                        break;
                    case "Sin falta":
                        c.setBackground(Color.GREEN);
                        break;
                    default:
                        c.setBackground(Color.WHITE);
                        break;
                }

                if (isSelected) {
                    c.setBackground(c.getBackground().darker());
                }

                return c;
            }
        });
 
    }//GEN-LAST:event_formWindowActivated

    private void CUIItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CUIItemStateChanged
        
        String seleccionado = (String) CUI.getSelectedItem();

        Boolean rojo = false;
        if (seleccionado != null && !seleccionado.isEmpty()) {
            String[] partes = seleccionado.split("-");
            if (partes.length > 0 && partes[0] != null && !partes[0].isEmpty()) {
                try {
                    long cui = Long.parseLong(partes[0].trim());

                    // 1️⃣ Cargar datos personales
                    String[] datos = this.controlador.traerDatos(cui);

                    Nombre.setText(datos[0]);
                    Apellido.setText(datos[1]);
                    Apellido1.setText(datos[2]);
                    Apellido2.setText((datos[3] != null && !datos[3].isEmpty()) ? datos[3] : " --- ");
                    Apellido3.setText((datos[4] != null && !datos[4].isEmpty()) ? datos[4] : " --- ");

                    // 2️⃣ Obtener registros diarios
                    List<Object[]> registros = this.controlador.obtenerFaltasPorEmpleado(cui);
                    DefaultTableModel modeloTabla = (DefaultTableModel) tablaFaltas.getModel();
                    modeloTabla.setRowCount(0);

                    // 3️⃣ Ordenar por fecha
                    registros.sort(Comparator.comparing(r -> LocalDate.parse((String) r[0])));

                    // 4️⃣ Obtener las faltas y horario del empleado
                    List<Falta> faltasEmpleado = this.controlador.obtenerFaltasPorCodigo(cui);
                    Horario horarioEmpleado = this.controlador.getModelo().getHorarios().stream()
                            .filter(h -> Objects.equals(h.getCodigo(), cui))
                            .findFirst()
                            .orElse(null);

                    boolean tieneAlmuerzo = (horarioEmpleado != null
                            && horarioEmpleado.getHoraAlmuerzo() != null
                            && horarioEmpleado.getFinAlmuerzo() != null);

                    // 5️⃣ Llenar tabla
                    for (Object[] r : registros) {
                        String dia = (String) r[0];
                        String entrada = (r[1] == null || ((String) r[1]).isEmpty()) ? "No registrada" : (String) r[1];
                        String entradaAlm = (r[2] == null || ((String) r[2]).isEmpty()) ? "No registrada" : (String) r[2];
                        String salidaAlm = (r[3] == null || ((String) r[3]).isEmpty()) ? "No registrada" : (String) r[3];
                        String salida = (r[4] == null || ((String) r[4]).isEmpty()) ? "No registrada" : (String) r[4];

                        if(entrada == null && entradaAlm == null && salidaAlm == null && salida == null ){
                            rojo = true;
                        }
                        
                        if (!tieneAlmuerzo) {
                            entradaAlm = "—";
                            salidaAlm = "—";
                        }

                        modeloTabla.addRow(new Object[]{dia, entrada, entradaAlm, salidaAlm, salida});
                    }

                    // 6️⃣ Colorear filas según motivo de falta
                    // 6️⃣ Colorear filas según motivo de falta
            tablaFaltas.setDefaultRenderer(Object.class, new DefaultTableCellRenderer() {
                @Override
                public Component getTableCellRendererComponent(JTable table, Object value,
                                                               boolean isSelected, boolean hasFocus,
                                                               int row, int column) {
                    Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                    String dia = (String) table.getValueAt(row, 0);
                    String entrada = (String) table.getValueAt(row, 1);
                    String entradaAlm = (String) table.getValueAt(row, 2);
                    String salidaAlm = (String) table.getValueAt(row, 3);
                    String salida = (String) table.getValueAt(row, 4);

                    Color colorBase = Color.GREEN;

                    // 🔴 Si todas las marcas del día están vacías → Falta total
                    // Si todas las horas relevantes (entrada y salida) están vacías o "No registradas" → Falta completa
                    if (
                        (entrada == null || entrada.equals("No registrada")) &&
                        (salida == null || salida.equals("No registrada")) &&
                        (
                            // El empleado tiene almuerzo y también faltó en esas marcas
                            (
                                (!"—".equals(entradaAlm)) &&
                                (!"—".equals(salidaAlm)) &&
                                ((entradaAlm == null || entradaAlm.equals("No registrada")) &&
                                 (salidaAlm == null || salidaAlm.equals("No registrada")))
                            )
                            // O no tiene almuerzo (ambas son "—")
                            || ("—".equals(entradaAlm) && "—".equals(salidaAlm))
                        )
                    ) {
                        colorBase = Color.RED;
                    } else {
                        // Si existe falta registrada, aplicar color correspondiente
                        Falta faltaDia = faltasEmpleado.stream()
                                .filter(f -> f.getDiaFalta().equals(dia))
                                .findFirst()
                                .orElse(null);

                        if (faltaDia != null) {
                            colorBase = switch (faltaDia.getMotivo()) {
                                case FALTA_COMPLETA -> Color.RED;
                                case ENTRADA_TARDE, SALIDA_TEMPRANA,
                                     ENTRADA_TARDE_DEL_ALMUERZO, SALIDA_TEMPRANA_AL_ALMUERZO -> Color.YELLOW;
                                case NO_MARCA_ENTRADA, NO_MARCA_SALIDA,
                                     NO_MARCA_SALIDA_ALMUERZO, NO_MARCA_ENTRADA_ALMUERZO -> Color.ORANGE;
                                default -> Color.GREEN;
                            };
                        }
                    }


                    c.setBackground(isSelected ? colorBase.darker() : colorBase);
                    return c;
                }
            });


                } catch (NumberFormatException ex) {
                    JOptionPane.showMessageDialog(this, "Error al convertir el CUI a número: " + ex.getMessage(),
                            "Error de formato", JOptionPane.ERROR_MESSAGE);
                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Error al obtener las faltas: " + ex.getMessage(),
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }



    }//GEN-LAST:event_CUIItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String fecha = Control.FechaCarta();
        String code = (String) CUI.getSelectedItem();

        String[] parte = code.split("-");
        
        String nombre = Nombre.getText();
        String ruta = controlador.getModelo().getHistorial().getUbicacionCartas();
        long codigo = Long.parseLong(parte[0].trim());
        
        
        
        try {
            Object item = CUI.getSelectedItem();
            if (item != null) {
                JOptionPane.showMessageDialog(this, "Informe creado para " + parte[1] , "Error", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se seleccionó ningún código", "Error", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El código debe ser un número válido", "Error de formato", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            controlador.getControlPDF().crearInforme(ruta, fecha, nombre, codigo);
        } catch (FileNotFoundException | DocumentException ex) {
            Logger.getLogger(Informe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Informe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Apellido;
    private javax.swing.JTextField Apellido1;
    private javax.swing.JTextField Apellido2;
    private javax.swing.JTextField Apellido3;
    private javax.swing.JComboBox<String> CUI;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTable colores;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablaFaltas;
    // End of variables declaration//GEN-END:variables
}
